// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: portfolio.proto

// Protobuf Java Version: 3.25.2
package org.rtportfolio.protobuf;

public final class PortfolioUpdate {
  private PortfolioUpdate() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PositionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.Position)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string symbol = 1;</code>
     * @return Whether the symbol field is set.
     */
    boolean hasSymbol();
    /**
     * <code>required string symbol = 1;</code>
     * @return The symbol.
     */
    java.lang.String getSymbol();
    /**
     * <code>required string symbol = 1;</code>
     * @return The bytes for symbol.
     */
    com.google.protobuf.ByteString
        getSymbolBytes();

    /**
     * <code>required double price = 2;</code>
     * @return Whether the price field is set.
     */
    boolean hasPrice();
    /**
     * <code>required double price = 2;</code>
     * @return The price.
     */
    double getPrice();

    /**
     * <code>required double qty = 3;</code>
     * @return Whether the qty field is set.
     */
    boolean hasQty();
    /**
     * <code>required double qty = 3;</code>
     * @return The qty.
     */
    double getQty();

    /**
     * <code>required double marketValue = 4;</code>
     * @return Whether the marketValue field is set.
     */
    boolean hasMarketValue();
    /**
     * <code>required double marketValue = 4;</code>
     * @return The marketValue.
     */
    double getMarketValue();

    /**
     * <code>required bool isPriceUpdated = 5;</code>
     * @return Whether the isPriceUpdated field is set.
     */
    boolean hasIsPriceUpdated();
    /**
     * <code>required bool isPriceUpdated = 5;</code>
     * @return The isPriceUpdated.
     */
    boolean getIsPriceUpdated();
  }
  /**
   * Protobuf type {@code protobuf.Position}
   */
  public static final class Position extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.Position)
      PositionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Position.newBuilder() to construct.
    private Position(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Position() {
      symbol_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Position();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.rtportfolio.protobuf.PortfolioUpdate.internal_static_protobuf_Position_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.rtportfolio.protobuf.PortfolioUpdate.internal_static_protobuf_Position_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.rtportfolio.protobuf.PortfolioUpdate.Position.class, org.rtportfolio.protobuf.PortfolioUpdate.Position.Builder.class);
    }

    private int bitField0_;
    public static final int SYMBOL_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object symbol_ = "";
    /**
     * <code>required string symbol = 1;</code>
     * @return Whether the symbol field is set.
     */
    @java.lang.Override
    public boolean hasSymbol() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string symbol = 1;</code>
     * @return The symbol.
     */
    @java.lang.Override
    public java.lang.String getSymbol() {
      java.lang.Object ref = symbol_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          symbol_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string symbol = 1;</code>
     * @return The bytes for symbol.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSymbolBytes() {
      java.lang.Object ref = symbol_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        symbol_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRICE_FIELD_NUMBER = 2;
    private double price_ = 0D;
    /**
     * <code>required double price = 2;</code>
     * @return Whether the price field is set.
     */
    @java.lang.Override
    public boolean hasPrice() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required double price = 2;</code>
     * @return The price.
     */
    @java.lang.Override
    public double getPrice() {
      return price_;
    }

    public static final int QTY_FIELD_NUMBER = 3;
    private double qty_ = 0D;
    /**
     * <code>required double qty = 3;</code>
     * @return Whether the qty field is set.
     */
    @java.lang.Override
    public boolean hasQty() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required double qty = 3;</code>
     * @return The qty.
     */
    @java.lang.Override
    public double getQty() {
      return qty_;
    }

    public static final int MARKETVALUE_FIELD_NUMBER = 4;
    private double marketValue_ = 0D;
    /**
     * <code>required double marketValue = 4;</code>
     * @return Whether the marketValue field is set.
     */
    @java.lang.Override
    public boolean hasMarketValue() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>required double marketValue = 4;</code>
     * @return The marketValue.
     */
    @java.lang.Override
    public double getMarketValue() {
      return marketValue_;
    }

    public static final int ISPRICEUPDATED_FIELD_NUMBER = 5;
    private boolean isPriceUpdated_ = false;
    /**
     * <code>required bool isPriceUpdated = 5;</code>
     * @return Whether the isPriceUpdated field is set.
     */
    @java.lang.Override
    public boolean hasIsPriceUpdated() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>required bool isPriceUpdated = 5;</code>
     * @return The isPriceUpdated.
     */
    @java.lang.Override
    public boolean getIsPriceUpdated() {
      return isPriceUpdated_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasSymbol()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPrice()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasQty()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMarketValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIsPriceUpdated()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, symbol_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeDouble(2, price_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeDouble(3, qty_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeDouble(4, marketValue_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeBool(5, isPriceUpdated_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, symbol_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, price_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, qty_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, marketValue_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, isPriceUpdated_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.rtportfolio.protobuf.PortfolioUpdate.Position)) {
        return super.equals(obj);
      }
      org.rtportfolio.protobuf.PortfolioUpdate.Position other = (org.rtportfolio.protobuf.PortfolioUpdate.Position) obj;

      if (hasSymbol() != other.hasSymbol()) return false;
      if (hasSymbol()) {
        if (!getSymbol()
            .equals(other.getSymbol())) return false;
      }
      if (hasPrice() != other.hasPrice()) return false;
      if (hasPrice()) {
        if (java.lang.Double.doubleToLongBits(getPrice())
            != java.lang.Double.doubleToLongBits(
                other.getPrice())) return false;
      }
      if (hasQty() != other.hasQty()) return false;
      if (hasQty()) {
        if (java.lang.Double.doubleToLongBits(getQty())
            != java.lang.Double.doubleToLongBits(
                other.getQty())) return false;
      }
      if (hasMarketValue() != other.hasMarketValue()) return false;
      if (hasMarketValue()) {
        if (java.lang.Double.doubleToLongBits(getMarketValue())
            != java.lang.Double.doubleToLongBits(
                other.getMarketValue())) return false;
      }
      if (hasIsPriceUpdated() != other.hasIsPriceUpdated()) return false;
      if (hasIsPriceUpdated()) {
        if (getIsPriceUpdated()
            != other.getIsPriceUpdated()) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasSymbol()) {
        hash = (37 * hash) + SYMBOL_FIELD_NUMBER;
        hash = (53 * hash) + getSymbol().hashCode();
      }
      if (hasPrice()) {
        hash = (37 * hash) + PRICE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getPrice()));
      }
      if (hasQty()) {
        hash = (37 * hash) + QTY_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getQty()));
      }
      if (hasMarketValue()) {
        hash = (37 * hash) + MARKETVALUE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getMarketValue()));
      }
      if (hasIsPriceUpdated()) {
        hash = (37 * hash) + ISPRICEUPDATED_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getIsPriceUpdated());
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.rtportfolio.protobuf.PortfolioUpdate.Position parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.rtportfolio.protobuf.PortfolioUpdate.Position parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.rtportfolio.protobuf.PortfolioUpdate.Position parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.rtportfolio.protobuf.PortfolioUpdate.Position parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.rtportfolio.protobuf.PortfolioUpdate.Position parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.rtportfolio.protobuf.PortfolioUpdate.Position parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.rtportfolio.protobuf.PortfolioUpdate.Position parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.rtportfolio.protobuf.PortfolioUpdate.Position parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.rtportfolio.protobuf.PortfolioUpdate.Position parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.rtportfolio.protobuf.PortfolioUpdate.Position parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.rtportfolio.protobuf.PortfolioUpdate.Position parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.rtportfolio.protobuf.PortfolioUpdate.Position parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.rtportfolio.protobuf.PortfolioUpdate.Position prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.Position}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.Position)
        org.rtportfolio.protobuf.PortfolioUpdate.PositionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.rtportfolio.protobuf.PortfolioUpdate.internal_static_protobuf_Position_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.rtportfolio.protobuf.PortfolioUpdate.internal_static_protobuf_Position_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.rtportfolio.protobuf.PortfolioUpdate.Position.class, org.rtportfolio.protobuf.PortfolioUpdate.Position.Builder.class);
      }

      // Construct using org.rtportfolio.protobuf.PortfolioUpdate.Position.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        symbol_ = "";
        price_ = 0D;
        qty_ = 0D;
        marketValue_ = 0D;
        isPriceUpdated_ = false;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.rtportfolio.protobuf.PortfolioUpdate.internal_static_protobuf_Position_descriptor;
      }

      @java.lang.Override
      public org.rtportfolio.protobuf.PortfolioUpdate.Position getDefaultInstanceForType() {
        return org.rtportfolio.protobuf.PortfolioUpdate.Position.getDefaultInstance();
      }

      @java.lang.Override
      public org.rtportfolio.protobuf.PortfolioUpdate.Position build() {
        org.rtportfolio.protobuf.PortfolioUpdate.Position result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.rtportfolio.protobuf.PortfolioUpdate.Position buildPartial() {
        org.rtportfolio.protobuf.PortfolioUpdate.Position result = new org.rtportfolio.protobuf.PortfolioUpdate.Position(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.rtportfolio.protobuf.PortfolioUpdate.Position result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.symbol_ = symbol_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.price_ = price_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.qty_ = qty_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.marketValue_ = marketValue_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.isPriceUpdated_ = isPriceUpdated_;
          to_bitField0_ |= 0x00000010;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.rtportfolio.protobuf.PortfolioUpdate.Position) {
          return mergeFrom((org.rtportfolio.protobuf.PortfolioUpdate.Position)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.rtportfolio.protobuf.PortfolioUpdate.Position other) {
        if (other == org.rtportfolio.protobuf.PortfolioUpdate.Position.getDefaultInstance()) return this;
        if (other.hasSymbol()) {
          symbol_ = other.symbol_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.hasPrice()) {
          setPrice(other.getPrice());
        }
        if (other.hasQty()) {
          setQty(other.getQty());
        }
        if (other.hasMarketValue()) {
          setMarketValue(other.getMarketValue());
        }
        if (other.hasIsPriceUpdated()) {
          setIsPriceUpdated(other.getIsPriceUpdated());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasSymbol()) {
          return false;
        }
        if (!hasPrice()) {
          return false;
        }
        if (!hasQty()) {
          return false;
        }
        if (!hasMarketValue()) {
          return false;
        }
        if (!hasIsPriceUpdated()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                symbol_ = input.readBytes();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 17: {
                price_ = input.readDouble();
                bitField0_ |= 0x00000002;
                break;
              } // case 17
              case 25: {
                qty_ = input.readDouble();
                bitField0_ |= 0x00000004;
                break;
              } // case 25
              case 33: {
                marketValue_ = input.readDouble();
                bitField0_ |= 0x00000008;
                break;
              } // case 33
              case 40: {
                isPriceUpdated_ = input.readBool();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object symbol_ = "";
      /**
       * <code>required string symbol = 1;</code>
       * @return Whether the symbol field is set.
       */
      public boolean hasSymbol() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string symbol = 1;</code>
       * @return The symbol.
       */
      public java.lang.String getSymbol() {
        java.lang.Object ref = symbol_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            symbol_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string symbol = 1;</code>
       * @return The bytes for symbol.
       */
      public com.google.protobuf.ByteString
          getSymbolBytes() {
        java.lang.Object ref = symbol_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          symbol_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string symbol = 1;</code>
       * @param value The symbol to set.
       * @return This builder for chaining.
       */
      public Builder setSymbol(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        symbol_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>required string symbol = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSymbol() {
        symbol_ = getDefaultInstance().getSymbol();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>required string symbol = 1;</code>
       * @param value The bytes for symbol to set.
       * @return This builder for chaining.
       */
      public Builder setSymbolBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        symbol_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private double price_ ;
      /**
       * <code>required double price = 2;</code>
       * @return Whether the price field is set.
       */
      @java.lang.Override
      public boolean hasPrice() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required double price = 2;</code>
       * @return The price.
       */
      @java.lang.Override
      public double getPrice() {
        return price_;
      }
      /**
       * <code>required double price = 2;</code>
       * @param value The price to set.
       * @return This builder for chaining.
       */
      public Builder setPrice(double value) {

        price_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>required double price = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPrice() {
        bitField0_ = (bitField0_ & ~0x00000002);
        price_ = 0D;
        onChanged();
        return this;
      }

      private double qty_ ;
      /**
       * <code>required double qty = 3;</code>
       * @return Whether the qty field is set.
       */
      @java.lang.Override
      public boolean hasQty() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required double qty = 3;</code>
       * @return The qty.
       */
      @java.lang.Override
      public double getQty() {
        return qty_;
      }
      /**
       * <code>required double qty = 3;</code>
       * @param value The qty to set.
       * @return This builder for chaining.
       */
      public Builder setQty(double value) {

        qty_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>required double qty = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearQty() {
        bitField0_ = (bitField0_ & ~0x00000004);
        qty_ = 0D;
        onChanged();
        return this;
      }

      private double marketValue_ ;
      /**
       * <code>required double marketValue = 4;</code>
       * @return Whether the marketValue field is set.
       */
      @java.lang.Override
      public boolean hasMarketValue() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>required double marketValue = 4;</code>
       * @return The marketValue.
       */
      @java.lang.Override
      public double getMarketValue() {
        return marketValue_;
      }
      /**
       * <code>required double marketValue = 4;</code>
       * @param value The marketValue to set.
       * @return This builder for chaining.
       */
      public Builder setMarketValue(double value) {

        marketValue_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>required double marketValue = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearMarketValue() {
        bitField0_ = (bitField0_ & ~0x00000008);
        marketValue_ = 0D;
        onChanged();
        return this;
      }

      private boolean isPriceUpdated_ ;
      /**
       * <code>required bool isPriceUpdated = 5;</code>
       * @return Whether the isPriceUpdated field is set.
       */
      @java.lang.Override
      public boolean hasIsPriceUpdated() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>required bool isPriceUpdated = 5;</code>
       * @return The isPriceUpdated.
       */
      @java.lang.Override
      public boolean getIsPriceUpdated() {
        return isPriceUpdated_;
      }
      /**
       * <code>required bool isPriceUpdated = 5;</code>
       * @param value The isPriceUpdated to set.
       * @return This builder for chaining.
       */
      public Builder setIsPriceUpdated(boolean value) {

        isPriceUpdated_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>required bool isPriceUpdated = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsPriceUpdated() {
        bitField0_ = (bitField0_ & ~0x00000010);
        isPriceUpdated_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protobuf.Position)
    }

    // @@protoc_insertion_point(class_scope:protobuf.Position)
    private static final org.rtportfolio.protobuf.PortfolioUpdate.Position DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.rtportfolio.protobuf.PortfolioUpdate.Position();
    }

    public static org.rtportfolio.protobuf.PortfolioUpdate.Position getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Position>
        PARSER = new com.google.protobuf.AbstractParser<Position>() {
      @java.lang.Override
      public Position parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Position> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Position> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.rtportfolio.protobuf.PortfolioUpdate.Position getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PortfolioOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.Portfolio)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .protobuf.Position position = 1;</code>
     */
    java.util.List<org.rtportfolio.protobuf.PortfolioUpdate.Position> 
        getPositionList();
    /**
     * <code>repeated .protobuf.Position position = 1;</code>
     */
    org.rtportfolio.protobuf.PortfolioUpdate.Position getPosition(int index);
    /**
     * <code>repeated .protobuf.Position position = 1;</code>
     */
    int getPositionCount();
    /**
     * <code>repeated .protobuf.Position position = 1;</code>
     */
    java.util.List<? extends org.rtportfolio.protobuf.PortfolioUpdate.PositionOrBuilder> 
        getPositionOrBuilderList();
    /**
     * <code>repeated .protobuf.Position position = 1;</code>
     */
    org.rtportfolio.protobuf.PortfolioUpdate.PositionOrBuilder getPositionOrBuilder(
        int index);

    /**
     * <code>required double totalNav = 2;</code>
     * @return Whether the totalNav field is set.
     */
    boolean hasTotalNav();
    /**
     * <code>required double totalNav = 2;</code>
     * @return The totalNav.
     */
    double getTotalNav();
  }
  /**
   * Protobuf type {@code protobuf.Portfolio}
   */
  public static final class Portfolio extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.Portfolio)
      PortfolioOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Portfolio.newBuilder() to construct.
    private Portfolio(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Portfolio() {
      position_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Portfolio();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.rtportfolio.protobuf.PortfolioUpdate.internal_static_protobuf_Portfolio_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.rtportfolio.protobuf.PortfolioUpdate.internal_static_protobuf_Portfolio_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.rtportfolio.protobuf.PortfolioUpdate.Portfolio.class, org.rtportfolio.protobuf.PortfolioUpdate.Portfolio.Builder.class);
    }

    private int bitField0_;
    public static final int POSITION_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<org.rtportfolio.protobuf.PortfolioUpdate.Position> position_;
    /**
     * <code>repeated .protobuf.Position position = 1;</code>
     */
    @java.lang.Override
    public java.util.List<org.rtportfolio.protobuf.PortfolioUpdate.Position> getPositionList() {
      return position_;
    }
    /**
     * <code>repeated .protobuf.Position position = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends org.rtportfolio.protobuf.PortfolioUpdate.PositionOrBuilder> 
        getPositionOrBuilderList() {
      return position_;
    }
    /**
     * <code>repeated .protobuf.Position position = 1;</code>
     */
    @java.lang.Override
    public int getPositionCount() {
      return position_.size();
    }
    /**
     * <code>repeated .protobuf.Position position = 1;</code>
     */
    @java.lang.Override
    public org.rtportfolio.protobuf.PortfolioUpdate.Position getPosition(int index) {
      return position_.get(index);
    }
    /**
     * <code>repeated .protobuf.Position position = 1;</code>
     */
    @java.lang.Override
    public org.rtportfolio.protobuf.PortfolioUpdate.PositionOrBuilder getPositionOrBuilder(
        int index) {
      return position_.get(index);
    }

    public static final int TOTALNAV_FIELD_NUMBER = 2;
    private double totalNav_ = 0D;
    /**
     * <code>required double totalNav = 2;</code>
     * @return Whether the totalNav field is set.
     */
    @java.lang.Override
    public boolean hasTotalNav() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required double totalNav = 2;</code>
     * @return The totalNav.
     */
    @java.lang.Override
    public double getTotalNav() {
      return totalNav_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTotalNav()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getPositionCount(); i++) {
        if (!getPosition(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < position_.size(); i++) {
        output.writeMessage(1, position_.get(i));
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeDouble(2, totalNav_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < position_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, position_.get(i));
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, totalNav_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.rtportfolio.protobuf.PortfolioUpdate.Portfolio)) {
        return super.equals(obj);
      }
      org.rtportfolio.protobuf.PortfolioUpdate.Portfolio other = (org.rtportfolio.protobuf.PortfolioUpdate.Portfolio) obj;

      if (!getPositionList()
          .equals(other.getPositionList())) return false;
      if (hasTotalNav() != other.hasTotalNav()) return false;
      if (hasTotalNav()) {
        if (java.lang.Double.doubleToLongBits(getTotalNav())
            != java.lang.Double.doubleToLongBits(
                other.getTotalNav())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getPositionCount() > 0) {
        hash = (37 * hash) + POSITION_FIELD_NUMBER;
        hash = (53 * hash) + getPositionList().hashCode();
      }
      if (hasTotalNav()) {
        hash = (37 * hash) + TOTALNAV_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getTotalNav()));
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.rtportfolio.protobuf.PortfolioUpdate.Portfolio parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.rtportfolio.protobuf.PortfolioUpdate.Portfolio parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.rtportfolio.protobuf.PortfolioUpdate.Portfolio parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.rtportfolio.protobuf.PortfolioUpdate.Portfolio parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.rtportfolio.protobuf.PortfolioUpdate.Portfolio parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.rtportfolio.protobuf.PortfolioUpdate.Portfolio parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.rtportfolio.protobuf.PortfolioUpdate.Portfolio parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.rtportfolio.protobuf.PortfolioUpdate.Portfolio parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.rtportfolio.protobuf.PortfolioUpdate.Portfolio parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.rtportfolio.protobuf.PortfolioUpdate.Portfolio parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.rtportfolio.protobuf.PortfolioUpdate.Portfolio parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.rtportfolio.protobuf.PortfolioUpdate.Portfolio parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.rtportfolio.protobuf.PortfolioUpdate.Portfolio prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.Portfolio}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.Portfolio)
        org.rtportfolio.protobuf.PortfolioUpdate.PortfolioOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.rtportfolio.protobuf.PortfolioUpdate.internal_static_protobuf_Portfolio_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.rtportfolio.protobuf.PortfolioUpdate.internal_static_protobuf_Portfolio_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.rtportfolio.protobuf.PortfolioUpdate.Portfolio.class, org.rtportfolio.protobuf.PortfolioUpdate.Portfolio.Builder.class);
      }

      // Construct using org.rtportfolio.protobuf.PortfolioUpdate.Portfolio.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (positionBuilder_ == null) {
          position_ = java.util.Collections.emptyList();
        } else {
          position_ = null;
          positionBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        totalNav_ = 0D;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.rtportfolio.protobuf.PortfolioUpdate.internal_static_protobuf_Portfolio_descriptor;
      }

      @java.lang.Override
      public org.rtportfolio.protobuf.PortfolioUpdate.Portfolio getDefaultInstanceForType() {
        return org.rtportfolio.protobuf.PortfolioUpdate.Portfolio.getDefaultInstance();
      }

      @java.lang.Override
      public org.rtportfolio.protobuf.PortfolioUpdate.Portfolio build() {
        org.rtportfolio.protobuf.PortfolioUpdate.Portfolio result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.rtportfolio.protobuf.PortfolioUpdate.Portfolio buildPartial() {
        org.rtportfolio.protobuf.PortfolioUpdate.Portfolio result = new org.rtportfolio.protobuf.PortfolioUpdate.Portfolio(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(org.rtportfolio.protobuf.PortfolioUpdate.Portfolio result) {
        if (positionBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            position_ = java.util.Collections.unmodifiableList(position_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.position_ = position_;
        } else {
          result.position_ = positionBuilder_.build();
        }
      }

      private void buildPartial0(org.rtportfolio.protobuf.PortfolioUpdate.Portfolio result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.totalNav_ = totalNav_;
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.rtportfolio.protobuf.PortfolioUpdate.Portfolio) {
          return mergeFrom((org.rtportfolio.protobuf.PortfolioUpdate.Portfolio)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.rtportfolio.protobuf.PortfolioUpdate.Portfolio other) {
        if (other == org.rtportfolio.protobuf.PortfolioUpdate.Portfolio.getDefaultInstance()) return this;
        if (positionBuilder_ == null) {
          if (!other.position_.isEmpty()) {
            if (position_.isEmpty()) {
              position_ = other.position_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePositionIsMutable();
              position_.addAll(other.position_);
            }
            onChanged();
          }
        } else {
          if (!other.position_.isEmpty()) {
            if (positionBuilder_.isEmpty()) {
              positionBuilder_.dispose();
              positionBuilder_ = null;
              position_ = other.position_;
              bitField0_ = (bitField0_ & ~0x00000001);
              positionBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPositionFieldBuilder() : null;
            } else {
              positionBuilder_.addAllMessages(other.position_);
            }
          }
        }
        if (other.hasTotalNav()) {
          setTotalNav(other.getTotalNav());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasTotalNav()) {
          return false;
        }
        for (int i = 0; i < getPositionCount(); i++) {
          if (!getPosition(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                org.rtportfolio.protobuf.PortfolioUpdate.Position m =
                    input.readMessage(
                        org.rtportfolio.protobuf.PortfolioUpdate.Position.PARSER,
                        extensionRegistry);
                if (positionBuilder_ == null) {
                  ensurePositionIsMutable();
                  position_.add(m);
                } else {
                  positionBuilder_.addMessage(m);
                }
                break;
              } // case 10
              case 17: {
                totalNav_ = input.readDouble();
                bitField0_ |= 0x00000002;
                break;
              } // case 17
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<org.rtportfolio.protobuf.PortfolioUpdate.Position> position_ =
        java.util.Collections.emptyList();
      private void ensurePositionIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          position_ = new java.util.ArrayList<org.rtportfolio.protobuf.PortfolioUpdate.Position>(position_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.rtportfolio.protobuf.PortfolioUpdate.Position, org.rtportfolio.protobuf.PortfolioUpdate.Position.Builder, org.rtportfolio.protobuf.PortfolioUpdate.PositionOrBuilder> positionBuilder_;

      /**
       * <code>repeated .protobuf.Position position = 1;</code>
       */
      public java.util.List<org.rtportfolio.protobuf.PortfolioUpdate.Position> getPositionList() {
        if (positionBuilder_ == null) {
          return java.util.Collections.unmodifiableList(position_);
        } else {
          return positionBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .protobuf.Position position = 1;</code>
       */
      public int getPositionCount() {
        if (positionBuilder_ == null) {
          return position_.size();
        } else {
          return positionBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .protobuf.Position position = 1;</code>
       */
      public org.rtportfolio.protobuf.PortfolioUpdate.Position getPosition(int index) {
        if (positionBuilder_ == null) {
          return position_.get(index);
        } else {
          return positionBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .protobuf.Position position = 1;</code>
       */
      public Builder setPosition(
          int index, org.rtportfolio.protobuf.PortfolioUpdate.Position value) {
        if (positionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePositionIsMutable();
          position_.set(index, value);
          onChanged();
        } else {
          positionBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Position position = 1;</code>
       */
      public Builder setPosition(
          int index, org.rtportfolio.protobuf.PortfolioUpdate.Position.Builder builderForValue) {
        if (positionBuilder_ == null) {
          ensurePositionIsMutable();
          position_.set(index, builderForValue.build());
          onChanged();
        } else {
          positionBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Position position = 1;</code>
       */
      public Builder addPosition(org.rtportfolio.protobuf.PortfolioUpdate.Position value) {
        if (positionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePositionIsMutable();
          position_.add(value);
          onChanged();
        } else {
          positionBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Position position = 1;</code>
       */
      public Builder addPosition(
          int index, org.rtportfolio.protobuf.PortfolioUpdate.Position value) {
        if (positionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePositionIsMutable();
          position_.add(index, value);
          onChanged();
        } else {
          positionBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Position position = 1;</code>
       */
      public Builder addPosition(
          org.rtportfolio.protobuf.PortfolioUpdate.Position.Builder builderForValue) {
        if (positionBuilder_ == null) {
          ensurePositionIsMutable();
          position_.add(builderForValue.build());
          onChanged();
        } else {
          positionBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Position position = 1;</code>
       */
      public Builder addPosition(
          int index, org.rtportfolio.protobuf.PortfolioUpdate.Position.Builder builderForValue) {
        if (positionBuilder_ == null) {
          ensurePositionIsMutable();
          position_.add(index, builderForValue.build());
          onChanged();
        } else {
          positionBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Position position = 1;</code>
       */
      public Builder addAllPosition(
          java.lang.Iterable<? extends org.rtportfolio.protobuf.PortfolioUpdate.Position> values) {
        if (positionBuilder_ == null) {
          ensurePositionIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, position_);
          onChanged();
        } else {
          positionBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Position position = 1;</code>
       */
      public Builder clearPosition() {
        if (positionBuilder_ == null) {
          position_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          positionBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Position position = 1;</code>
       */
      public Builder removePosition(int index) {
        if (positionBuilder_ == null) {
          ensurePositionIsMutable();
          position_.remove(index);
          onChanged();
        } else {
          positionBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Position position = 1;</code>
       */
      public org.rtportfolio.protobuf.PortfolioUpdate.Position.Builder getPositionBuilder(
          int index) {
        return getPositionFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .protobuf.Position position = 1;</code>
       */
      public org.rtportfolio.protobuf.PortfolioUpdate.PositionOrBuilder getPositionOrBuilder(
          int index) {
        if (positionBuilder_ == null) {
          return position_.get(index);  } else {
          return positionBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .protobuf.Position position = 1;</code>
       */
      public java.util.List<? extends org.rtportfolio.protobuf.PortfolioUpdate.PositionOrBuilder> 
           getPositionOrBuilderList() {
        if (positionBuilder_ != null) {
          return positionBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(position_);
        }
      }
      /**
       * <code>repeated .protobuf.Position position = 1;</code>
       */
      public org.rtportfolio.protobuf.PortfolioUpdate.Position.Builder addPositionBuilder() {
        return getPositionFieldBuilder().addBuilder(
            org.rtportfolio.protobuf.PortfolioUpdate.Position.getDefaultInstance());
      }
      /**
       * <code>repeated .protobuf.Position position = 1;</code>
       */
      public org.rtportfolio.protobuf.PortfolioUpdate.Position.Builder addPositionBuilder(
          int index) {
        return getPositionFieldBuilder().addBuilder(
            index, org.rtportfolio.protobuf.PortfolioUpdate.Position.getDefaultInstance());
      }
      /**
       * <code>repeated .protobuf.Position position = 1;</code>
       */
      public java.util.List<org.rtportfolio.protobuf.PortfolioUpdate.Position.Builder> 
           getPositionBuilderList() {
        return getPositionFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.rtportfolio.protobuf.PortfolioUpdate.Position, org.rtportfolio.protobuf.PortfolioUpdate.Position.Builder, org.rtportfolio.protobuf.PortfolioUpdate.PositionOrBuilder> 
          getPositionFieldBuilder() {
        if (positionBuilder_ == null) {
          positionBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              org.rtportfolio.protobuf.PortfolioUpdate.Position, org.rtportfolio.protobuf.PortfolioUpdate.Position.Builder, org.rtportfolio.protobuf.PortfolioUpdate.PositionOrBuilder>(
                  position_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          position_ = null;
        }
        return positionBuilder_;
      }

      private double totalNav_ ;
      /**
       * <code>required double totalNav = 2;</code>
       * @return Whether the totalNav field is set.
       */
      @java.lang.Override
      public boolean hasTotalNav() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required double totalNav = 2;</code>
       * @return The totalNav.
       */
      @java.lang.Override
      public double getTotalNav() {
        return totalNav_;
      }
      /**
       * <code>required double totalNav = 2;</code>
       * @param value The totalNav to set.
       * @return This builder for chaining.
       */
      public Builder setTotalNav(double value) {

        totalNav_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>required double totalNav = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTotalNav() {
        bitField0_ = (bitField0_ & ~0x00000002);
        totalNav_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protobuf.Portfolio)
    }

    // @@protoc_insertion_point(class_scope:protobuf.Portfolio)
    private static final org.rtportfolio.protobuf.PortfolioUpdate.Portfolio DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.rtportfolio.protobuf.PortfolioUpdate.Portfolio();
    }

    public static org.rtportfolio.protobuf.PortfolioUpdate.Portfolio getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Portfolio>
        PARSER = new com.google.protobuf.AbstractParser<Portfolio>() {
      @java.lang.Override
      public Portfolio parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Portfolio> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Portfolio> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.rtportfolio.protobuf.PortfolioUpdate.Portfolio getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_Position_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_Position_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_Portfolio_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_Portfolio_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017portfolio.proto\022\010protobuf\"c\n\010Position\022" +
      "\016\n\006symbol\030\001 \002(\t\022\r\n\005price\030\002 \002(\001\022\013\n\003qty\030\003 " +
      "\002(\001\022\023\n\013marketValue\030\004 \002(\001\022\026\n\016isPriceUpdat" +
      "ed\030\005 \002(\010\"C\n\tPortfolio\022$\n\010position\030\001 \003(\0132" +
      "\022.protobuf.Position\022\020\n\010totalNav\030\002 \002(\001B+\n" +
      "\030org.rtportfolio.protobufB\017PortfolioUpda" +
      "te"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_protobuf_Position_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_Position_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_Position_descriptor,
        new java.lang.String[] { "Symbol", "Price", "Qty", "MarketValue", "IsPriceUpdated", });
    internal_static_protobuf_Portfolio_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protobuf_Portfolio_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_Portfolio_descriptor,
        new java.lang.String[] { "Position", "TotalNav", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
